Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.10.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  
  RouteTable: 
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC

  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.1.0/24

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: String
      VpcId: !Ref VPC

  
  VPCEndPointForS3:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      PolicyDocument: Json
      PrivateDnsEnabled: True
      RouteTableIds: 
        - { "Fn::ImportValue": !Sub "${PJPrefix}-private-route-a" }
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      VpcEndpointType: Gateway
      VpcId: !Ref VPC

  VPCEndPointForDyn:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      PolicyDocument: Json
      PrivateDnsEnabled: True
      RouteTableIds: 
        - { "Fn::ImportValue": !Sub "${PJPrefix}-private-route-a" }
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.dynamodb"
      VpcEndpointType: Gateway
      VpcId: !Ref VPC
  
  VPCEndPointForKDS:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      PolicyDocument: Json
      PrivateDnsEnabled: True
      SecurityGroupIds: 
        - { "Fn::ImportValue": !Sub "${PJPrefix}-private-route-a" }
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.kinesisstreams"
      VpcEndpointType: Interface
      VpcId: !Ref VPC

  VPCEndPointForSSM:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      PolicyDocument: Json
      PrivateDnsEnabled: True
      SecurityGroupIds: 
        - { "Fn::ImportValue": !Sub "${PJPrefix}-private-route-a" }
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ssm"
      VpcEndpointType: Interface
      VpcId: !Ref VPC

  VPCEndPointForSSMMsg:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      PolicyDocument: Json
      PrivateDnsEnabled: True
      SecurityGroupIds: 
        - { "Fn::ImportValue": !Sub "${PJPrefix}-private-route-a" }
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ssmmessage"
      VpcEndpointType: Interface
      VpcId: !Ref VPC
  
  VPCEndPointForEC2Msg:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      PolicyDocument: Json
      PrivateDnsEnabled: True
      SecurityGroupIds: 
        - { "Fn::ImportValue": !Sub "${PJPrefix}-private-route-a" }
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ec2message"
      VpcEndpointType: Interface
      VpcId: !Ref VPC

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0c3fd0f5d33134a76
      SecurityGroupIds:
        - !Ref SecurityGroup
      SubnetId: subnet-sctv01234
      Tags:
        -
          Key: Name
          Value: sctvーwebserver   